services:
  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    environment:
      - FRIGATE_MQTT_USER=${FRIGATE_MQTT_USER}
      - FRIGATE_MQTT_PASSWORD=${FRIGATE_MQTT_PASSWORD}
      - FRIGATE_RTSP_HOST=${FRIGATE_RTSP_HOST}
      - FRIGATE_RTSP_USER=${FRIGATE_RTSP_USER}
      - FRIGATE_RTSP_PASSWORD=${FRIGATE_RTSP_PASSWORD}
    networks:
      macvlan:
        ipv4_address: ${FRIGATE_IPV4_ADDRESS}
      mqtt:
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/config/
      - ./storage/:/media/frigate/
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    shm_size: "512mb"
    stop_grace_period: 30s
    restart: unless-stopped

networks:
  macvlan:
    name: ${NETWORK_NAME}
    external: true
  mqtt:
    name: mqtt
    external: true
